// packages/website/src/components/Navbar.svelte
<script>
    import { _, locale, locales } from 'svelte-i18n';
    import { onMount } from 'svelte';
    import { getCookie, setCookie } from '../utils/cookies';
    import { changeLang, getCurrentLang } from '../utils/language';
    import { stores } from '@sapper/app';
    const { page } = stores();

    export let segment;

    let sidenav, dropdownNavMain, dropdownNavMobile;
    onMount(() => {
        M.Sidenav.init(sidenav);
        M.Dropdown.init(dropdownNavMain);
        M.Dropdown.init(dropdownNavMobile);
    });
</script>

<div class="navbar-fixed">
    <nav class="white" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="/" class="brand-logo">
                <img height="28" src="/img/logo-black.jpg" alt="Logo" />
            </a>
            <ul id="nav" class="right hide-on-med-and-down">
                <li class:active="{segment === undefined && $page.path === '/'}">
                    <a rel="prefetch" href="/">{$_('nav.home')}</a>
                </li>
                <li class:active="{segment === 'training'}">
                    <a rel="prefetch" href="/training/">{$_('nav.training')}</a>
                </li>
                <li class:active="{segment === 'interclub'}">
                    <a rel="prefetch" href="/interclub/">{$_('nav.interclub')}</a>
                </li>
                <li class:active="{segment === 'contact'}">
                    <a rel="prefetch" href="/contact/">{$_('nav.contact')}</a>
                </li>
                <li class:active="{segment === 'about'}">
                    <a rel="prefetch" href="/about/">{$_('nav.about')}</a>
                </li>
                <li class:active="{segment === 'login'}">
                    <a rel="prefetch" href="/login/">{$_('nav.login')}</a>
                </li>
                <li>
                    <ul id="language-selector" class="dropdown-content">
                        <li>
                            <a href="#!" on:click="{() => (changeLang($locale))}">{getCurrentLang().toUpperCase()}</a>
                        </li>
                        {#each $locales as lang} {#if lang !== getCurrentLang()}
                        <li><a href="#!" on:click="{() => (changeLang(lang))}">{lang.toUpperCase()}</a></li>
                        {/if} {/each}
                    </ul>
                    <a class="dropdown-trigger" href="#!" data-target="language-selector" bind:this="{dropdownNavMain}">
                        {$locale.toUpperCase()}
                        <i class="material-icons right">arrow_drop_down</i>
                    </a>
                </li>
            </ul>
            <a href="#!" data-target="nav-mobile" class="sidenav-trigger">
                <i class="material-icons">menu</i>
            </a>
            <ul id="nav-mobile" class="sidenav" bind:this="{sidenav}">
                <li>
                    <ul id="language-selector-mobile" class="dropdown-content">
                        <li>
                            <a href="#!" on:click="{() => (changeLang($locale))}">{getCurrentLang().toUpperCase()}</a>
                        </li>
                        {#each $locales as lang} {#if lang !== getCurrentLang()}
                        <li><a href="#!" on:click="{() => (changeLang(lang))}">{lang.toUpperCase()}</a></li>
                        {/if} {/each}
                    </ul>
                    <a
                        class="dropdown-trigger"
                        href="#!"
                        data-target="language-selector-mobile"
                        bind:this="{dropdownNavMobile}"
                    >
                        {$locale.toUpperCase()}
                        <i class="material-icons right">arrow_drop_down</i>
                    </a>
                </li>
                <li class="divider"></li>
                <li class:active="{segment === undefined && $page.path === '/'}">
                    <a rel="prefetch" href="/">{$_('nav.home')}</a>
                </li>
                <li class:active="{segment === 'training'}">
                    <a rel="prefetch" href="/training/">{$_('nav.training')}</a>
                </li>
                <li class:active="{segment === 'interclub'}">
                    <a rel="prefetch" href="/interclub/">{$_('nav.interclub')}</a>
                </li>
                <li class:active="{segment === 'contact'}">
                    <a rel="prefetch" href="/contact/">{$_('nav.contact')}</a>
                </li>
                <li class:active="{segment === 'about'}">
                    <a rel="prefetch" href="/about/">{$_('nav.about')}</a>
                </li>
                <li class:active="{segment === 'login'}">
                    <a rel="prefetch" href="/login/">{$_('nav.login')}</a>
                </li>
            </ul>
        </div>
    </nav>
</div>

// packages/website/src/components/Navbar.tsx
import React from 'react'

import * as MaterializeCss from 'react-materialize'
import { Icon, NavItem, Dropdown, Divider } from 'react-materialize'
import logo from '../images/logo-black.jpg'

const LanguageSelector: React.FC<{ id: string; triggerClassName: string }> = ({ id, triggerClassName }) => (
    <Dropdown
        id={id}
        options={{
            alignment: 'left',
            autoTrigger: true,
            closeOnClick: true,
            constrainWidth: true,
            container: null,
            coverTrigger: true,
            hover: false,
            inDuration: 150,
            outDuration: 250,
        }}
        trigger={
            <a className={triggerClassName} href="#!">
                EN <Icon right>arrow_drop_down</Icon>
            </a>
        }
    >
        <a href="#!">EN</a>
        <a href="#!">DE</a>
    </Dropdown>
)

const LanguageSelectorWithDivider: React.FC<{ id: string; triggerClassName: string }> = ({ id, triggerClassName }) => (
    <>
        <LanguageSelector id={id} triggerClassName={triggerClassName} />
        <div className={triggerClassName}>
            <Divider />
        </div>
    </>
)

export const Navbar: React.FC = () => {
    return (
        <MaterializeCss.Navbar
            className="white"
            alignLinks="right"
            fixed={true}
            centerChildren={true}
            brand={
                <a className="brand-logo" href="/">
                    <img height="28" src={logo} alt="Logo" />
                </a>
            }
            menuIcon={<Icon>menu</Icon>}
            options={{
                draggable: true,
                edge: 'left',
                inDuration: 250,
                outDuration: 200,
                preventScrolling: true,
            }}
        >
            <LanguageSelectorWithDivider id="language-selector-1" triggerClassName="hide-on-large-only" />
            <NavItem href="/">Home</NavItem>
            <NavItem href="/training">Training</NavItem>
            <NavItem href="/interclub">Interclub</NavItem>
            <NavItem href="/contact">Contact</NavItem>
            <NavItem href="/about">About</NavItem>
            <NavItem href="/login">Login</NavItem>
            <LanguageSelector id="language-selector-2" triggerClassName="hide-on-med-and-down" />
        </MaterializeCss.Navbar>
    )
}

export default Navbar
